### ISSUE TITLE
Create a voting system.

### ISSUE THREAD

**Issue by Lanred-Dev** [monke-mob/monke-activities#10]
Complements #9 

### Progress
- [x] Server
- [x] Client
- [x] User Interface

### Server
The server needs to be able to communicate with the round system to tell it what map and game modes where selected. The server should take map votes at first then once voting has concluded for maps it should send over the available game modes for that map.

### Client
The client needs to be able to send requests to the server for whenever a game mode is chosen. Everything should work in parallel with the server needs.

### User Interface
The user interface should include two prompts, one for the maps and one for the game modes. It should display who voted on what, a timer with the time left to vote, and should display the results at the end.

**Comment by Squidsss** [comment]
holy moly

**Comment by Lanred-Dev** [comment]
It still needs polishing but is fully implemented.
