### ISSUE TITLE
Instead of limiting the player to premade avatars, how about a avatar editor?

### ISSUE THREAD

**Issue by Lanred-Dev** [monke-mob/monke-activities#11]
### Proposal 
Currently the plan is for us to make avatars that the player can purchase. While there is no general problem with this, it does not give the player complete freedom over **their** avatar. So I propose, instead of just premade avatars why don't we have a avatar editor? The avatar editor is exactly what it sounds like, a editor for the players avatar. Instead of us making the skins we can make the accessories and colors for player avatars and players can determine what goes onto their avatar. This gives the player way more creative freedom and allows them to mix and match items to create unique avatars. This idea does not fully remove premade avatars though as we can still make them and the players can add/subtract away from them.

### Needed actions
In order for this to happen we need to convert all existing avatars to a more scriptable format, like a Lua table, so that the items in a premade avatar can be easily fetched by scripts. We would also need to design a avatar editor, way to save avatars, and create, as mentioned above, a Lua table for each accessory/item.

_**Please list your comments below.**_

**Comment by homiemace** [comment]
I feel it is a great idea and can let the players express themselves more, but I still think we should have the other skins I had made like "donke" as bases that people can build off. It would take some work but it would pay off for sure.

**Comment by Lanred-Dev** [comment]
> but I still think we should have the other skins I had made like "donke" as bases that people can build off.

As I stated, those will stay.

**Comment by Lanred-Dev** [comment]
Needs an issue.
