### ISSUE TITLE
Redo the monkey head.

### ISSUE THREAD

**Issue by homiemace** [monke-mob/monke-activities#15]
The monkey head may lead to more harm than good if the head isn't changed considering it is still Roblox's IP. The head needs to be recreated and appear like what Roblox's monkey head, the current model, looks like. It needs to be as close as possible but enough to claim it as monke mob's IP.

### Pictures
![image](https://github.com/monke-mob/monke-activities/assets/90294477/7983c98b-a475-409e-9c13-0892d3d5af2a)
![image](https://github.com/monke-mob/monke-activities/assets/90294477/280b797c-436f-4c00-8061-771c701fa293)
![image](https://github.com/monke-mob/monke-activities/assets/90294477/49e6ee07-66af-4e27-aef7-a8c2c5787bd4)
![image](https://github.com/monke-mob/monke-activities/assets/90294477/27294e7f-db29-4280-b544-c65ef33d9b83)
![image](https://github.com/monke-mob/monke-activities/assets/90294477/14e12988-ebff-4d8c-80e7-b336662abe87)
![image](https://github.com/monke-mob/monke-activities/assets/90294477/95e7bc6c-6450-4f4b-885c-96d4aa83341a)

- [x] Model
- [x] Texture

**Comment by bloxy1noob** [comment]
hey homie, i’ll do it today but do you want it to be low poly or normal

**Comment by homiemace** [comment]
stick with low poly, if not whatever u think will look best

**Comment by homiemace** [comment]
needs to be noticeably different to avoid copyright of course but as close as you can

**Comment by bloxy1noob** [comment]
ok

**Comment by bloxy1noob** [comment]
yeah homie we definitely need to update the monkey considering roblox’s new TOS, they will not allow games to use items made by roblox that are off sale

**Comment by homiemace** [comment]
yup, exactly why i'm asking you to do this. what sucks is all the other skins use unreleased roblox hats so i may have u redo those only if u have time and want to of course

**Comment by bloxy1noob** [comment]
yeah i would want to do them i think i feel happier making things that aren’t trees

**Comment by homiemace** [comment]
yeah lol go ahead

**Comment by bloxy1noob** [comment]
hey homie could you send the texture?

**Comment by homiemace** [comment]
yeah hold up

**Comment by bloxy1noob** [comment]
i saw you send me the blend file 
i got the texture now

**Comment by homiemace** [comment]
u prob wanna make a new texture tho

**Comment by bloxy1noob** [comment]
oh ok

**Comment by bloxy1noob** [comment]
![Screenshot 2023-09-21 at 2 27 46 PM](https://github.com/monke-mob/monke-activities/assets/133997069/3300b494-3fcb-4015-9af4-7e340a33f7ee)
![Screenshot 2023-09-21 at 2 27 37 PM](https://github.com/monke-mob/monke-activities/assets/133997069/09b8a579-e248-458e-ab04-6259383c7494)
![Screenshot 2023-09-21 at 2 27 32 PM](https://github.com/monke-mob/monke-activities/assets/133997069/a26557a6-b703-42ed-b03f-c958514b24bf)

**Comment by bloxy1noob** [comment]
anything i should change?

**Comment by homiemace** [comment]
i do feel the ears look a bit like shrek ears? maybe make them less deep.

**Comment by bloxy1noob** [comment]
lol ok

**Comment by homiemace** [comment]
more like a monkey

**Comment by Lanred-Dev** [comment]
Yea the ears do look a little weird imo

**Comment by bloxy1noob** [comment]
im tryna fix them

**Comment by bloxy1noob** [comment]
![Screenshot 2023-09-21 at 3 06 42 PM](https://github.com/monke-mob/monke-activities/assets/133997069/98438bbe-ed19-4055-aaa1-31485e12c4e5)

**Comment by homiemace** [comment]
can i see another view?

**Comment by bloxy1noob** [comment]
![Screenshot 2023-09-21 at 3 11 21 PM](https://github.com/monke-mob/monke-activities/assets/133997069/774ad41f-5fcc-470a-a266-46373f7a0ecd)

**Comment by bloxy1noob** [comment]
![Screenshot 2023-09-21 at 3 11 45 PM](https://github.com/monke-mob/monke-activities/assets/133997069/1200a654-70ab-402a-91d5-3cffd1596f7f)

**Comment by homiemace** [comment]
![image](https://github.com/monke-mob/monke-activities/assets/90294477/91c9c1bd-3b70-4e9d-a1c5-550d5d5edba9)
sorry to be picky, i feel they should go out more like this.

**Comment by bloxy1noob** [comment]
ahhhh ok
thank you for showing me

**Comment by bloxy1noob** [comment]
i get it now

**Comment by homiemace** [comment]
maybe a bit smaller to kinda look like roblox's version tho

**Comment by bloxy1noob** [comment]
ok

**Comment by bloxy1noob** [comment]
homie ill come back later i gtg

**Comment by homiemace** [comment]
kk

**Comment by bloxy1noob** [comment]
![IMG_7407](https://github.com/monke-mob/monke-activities/assets/133997069/01b100b7-884e-41fa-ba30-f9d1d58d4469)

**Comment by homiemace** [comment]
holy moly is that a rat?

**Comment by bloxy1noob** [comment]
the render looks even better

**Comment by bloxy1noob** [comment]
yes it is a rat
chunky cheese

**Comment by bloxy1noob** [comment]
a friend drew a rough rat drawing and i made it

**Comment by bloxy1noob** [comment]
i just noticed some textures are funky but its still a wip

**Comment by bloxy1noob** [comment]
![the real rat and monke](https://github.com/monke-mob/monke-activities/assets/133997069/bc1b2530-d3a3-4313-8105-f0989120c1ec)

**Comment by homiemace** [comment]
looks sick, we should prob just use this for dev work but it looks amazing.

**Comment by bloxy1noob** [comment]
yeah i just wanted to show you

**Comment by homiemace** [comment]
yeah its really cool, all good

**Comment by homiemace** [comment]
im so excited, i really wanna test for it.

**Comment by bloxy1noob** [comment]
https://meet.google.com/kfy-vhdn-yjy

**Comment by bloxy1noob** [comment]
hey homie ill send you a new one

**Comment by bloxy1noob** [comment]
https://meet.google.com/dgt-prsh-phh

**Comment by bloxy1noob** [comment]
@homiemace

**Comment by homiemace** [comment]
![businessmonkev2](https://github.com/monke-mob/monke-activities/assets/90294477/4fb50e73-7cf4-40c8-a346-17d8ef501957)

**Comment by bloxy1noob** [comment]
amazing

**Comment by bloxy1noob** [comment]
homie ill make a google meet so i can work on the head texture, join if you are able to
https://meet.google.com/jxf-rfpx-sjq

**Comment by bloxy1noob** [comment]
https://meet.google.com/ukx-zdoa-vcx

**Comment by bloxy1noob** [comment]
https://meet.google.com/jjs-obbu-ncc

**Comment by bloxy1noob** [comment]
hey homie im able to work again send me a message when you can googl meet

**Comment by bloxy1noob** [comment]
https://meet.google.com/zxr-tzuu-tpf

**Comment by bloxy1noob** [comment]
https://meet.google.com/csx-woez-pon

**Comment by bloxy1noob** [comment]
homie you there?

**Comment by bloxy1noob** [comment]
![Screenshot 2023-09-29 at 9 08 02 PM](https://github.com/monke-mob/monke-activities/assets/133997069/417f7355-9dcb-482f-8e45-8288ab2df2b2)

**Comment by bloxy1noob** [comment]
homie dont forget to join back to the call

**Comment by bloxy1noob** [comment]
https://meet.google.com/sxo-ycvk-ajg

**Comment by homiemace** [comment]
![image](https://github.com/monke-mob/monke-activities/assets/90294477/5f307014-ec43-439f-9f74-ce2fff70f5a3)
Final texture and model for the head at least.

**Comment by Lanred-Dev** [comment]
It seems good, moving to Staging.
