### ISSUE TITLE
How about we redo lobby, adding a village with side quests?

### ISSUE THREAD

**Issue by homiemace** [monke-mob/monke-activities#29]
### Proposal
While the current lobby has no issues, it is lacking two things. Engagement, Life, and Space. So why not redo it? We could redo the lobby to include a lot more open space, environment, life, and even engagement. It would be nice to, in this redone lobby, have some models made such as jungle trees, think of Endor from Star Wars, and a village of sorts. This helps add to the overall environment which is monkeys, which are often associated with a jungle. As for engagement, we could have these side quests in the village where once completed could reward the players with a special game mode, for one round, boosts, currency, etc. This would keep waiting players engaged because they know that they get something for completing the tasks and it helps to keep waiting players doing something. These tasks would be shared with the server, and would not be relative to each player.

### Needed actions
Depending on how we imagine it looking, we would need a bit of modeling for the trees and the village huts/houses. This would also take some building to place these models and make the layout for the entire lobby depicting where we will put things so it's a lot easier to create once we have the models. We would need programming to give the prompts for the side quests and dialog of the NPCs if we end up doing that.

_**Please list your comments below.**_

**Comment by Lanred-Dev** [comment]
I think redoing the lobby is a great idea, I feel as if this new idea fits in with the game more and can help with keeping the player engaged! I approve 👍🏼

**Comment by bloxy1noob** [comment]
Yeah I think this would be amazing, I think I have a lot of ideas on trees, maybe palm trees or a little beach

**Comment by Squidsss** [comment]
I think remaking the lobby is a  good idea, I also really like the side quest idea. I also have a similar idea where players could play games in the lobby and earn little rewards while waiting for the next game.

**Comment by 0Bec** [comment]
yes

**Comment by Lanred-Dev** [comment]
Needs an issue.
