### ISSUE TITLE
Trees/foliage.

### ISSUE THREAD

**Issue by homiemace** [monke-mob/monke-activities#3]
### Progress

- [x] First tree
- [x] Second tree
- [x] Third tree
- [x] Fourth tree

**_I need to have the old tree redone, and two others made if that is alright._** I feel as if you should _do what you did with the other tree you had made @bloxy1noob,_ try to make them look different enough but follow the same kind of low poly theme you went with. If you need more references ask me but I will post the original tree and the one you made along with it to look at. Along with a photo of the lobby to get the feel for it.

![image](https://github.com/monke-mob/monke-activities/assets/90294477/ed83356b-8aa5-4d5b-85fb-e354d1066cae)
![image](https://github.com/monke-mob/monke-activities/assets/90294477/5ee6f016-9d9b-441d-8b64-47a70ea24ea0)

**Comment by bloxy1noob** [comment]
homie since you are currently offline on roblox, i am saying this here
i will add everyone i have added on my second account, bloxy_zack
<img width="1138" alt="Screenshot 2023-09-16 at 10 41 35 PM" src="https://github.com/monke-mob/monke-activities/assets/133997069/3eff57b3-1a23-42ab-be82-7cfbe6ea79ee">
just accept the friend request

**Comment by bloxy1noob** [comment]
i need to unfriend you on my main
if anyone asks why i unfriended them i sent them a friend request on this one

**Comment by homiemace** [comment]
all good, i just saw these sorry.

**Comment by homiemace** [comment]
have been sick, should have done this last night lol

**Comment by Lanred-Dev** [comment]
Change priority to urgent so that this issue can be closed.

**Comment by homiemace** [comment]
![image](https://github.com/monke-mob/monke-activities/assets/90294477/773f1197-d5bf-4c7a-87d4-013f2c2395c1)
Final product.
