### ISSUE TITLE
Add "Eternal Banana Race".

### ISSUE THREAD

**Issue by homiemace** [monke-mob/monke-activities#38]
### **Eternal Banana Race**

I suggest we add this song to the game and incorporate it into some of the minigames that fit, you could consider it a multi-purpose song used for many minigames without a set theme.

**Comment by Lanred-Dev** [comment]
Holding off on assignments until an audio system is created.

**Comment by homiemace** [comment]
Good point, my bad.

**Comment by Lanred-Dev** [comment]
Audio ID: rbxassetid://16560984878
