### ISSUE TITLE
Should tails be added on characters?

### ISSUE THREAD

**Issue by homiemace** [monke-mob/monke-activities#43]
### Proposal
I believe adding tails to the skins would be a wonderful addition to the game.

![image](https://github.com/monke-mob/monke-activities/assets/90294477/6054bd41-edb2-4895-9ef4-e12729b09310)

### Needed actions
To accomplish this, we would need to create a detailed mesh for the tail and properly attach Motor6Ds to it. Then, if we intend to animate the tail, we would need to design and incorporate bones in Blender. This step would allow for greater flexibility and control over the tail's movements, allowing us to achieve a more realistic and polished end result.

_**Please list your comments below.**_

**Comment by Lanred-Dev** [comment]
I don't like the tail but I could see it giving some users more customization.

**Comment by Lanred-Dev** [comment]
From Senpoo: Yes, it adds uniqueness

**Comment by bloxy1noob** [comment]
I think it should be added, pls
