### ISSUE TITLE
Instead of modes being all in one place how about separate places?

### ISSUE THREAD

**Issue by Lanred-Dev** [monke-mob/monke-activities#51]
### Proposal
The current idea for the game is to have all of the maps and modes be contained in the same place, however what if they were all hosted in separate places? Doing this would reduce code complexity and overall project size while also removing potential things such as memory leaks due to modes having to be cleaned up every time they are finished. Take this, for example, we have a mode, call it 'zombies', and another mode, call it 'climbing'. We also have two maps, 'lab' and 'city'. Having all of these be hosted in the same game, and in return, the same code base would be quite complex due to the modes having to be loadable, removable, and compatible with existing systems, as well as maps and their scripts. But if these were hosted in different places and players were just simply teleported to them to start the game it would reduce game size and code complexity. Players would simply be teleported back with their party to choose another mode and map after that round is over. I feel as if this idea works out well due to this game being more of a party game with longer rounds (like 5-15min). This in return solves another problem, players losing their interest while having to wait for a round to end. Because players could simply join a public lobby and then vote with other players to start a game immediately, instead of having to wait. This also allows bigger groups to have private games where they can choose what mode and map to play instead of being at the hands of randomness.

### Needed actions
This proposal does not come without its hefty amount of work though, in order for this to be achieved the supporting systems would have to be implemented, such as a new round system, party system, and lobby system. A way would also have to be found to easily distribute modes and other systems to each place without us having to manually update them. In the short run, it would take a lot of work but in the long run, it would editing code a lot easier, and I mean it. It would also for @monke-mob/builders to easily edit maps because they would each have their own place.

_**Please list your comments below.**_

**Comment by bloxy1noob** [comment]
I really think this is a good idea of having the maps in their own places because it would make it a lot easier later on 👍🏻

**Comment by homiemace** [comment]
This is a much better idea than the initial plan of having one game for all the maps. The new approach is more organized, with less clutter, and makes it easy to navigate the maps in the future.

**Comment by Lanred-Dev** [comment]
I am aware that this proposal was already accepted but what if it was the other way around for storing modes and maps? I feel as if it would actually be a lot easier to have each mode have its own place and the maps be updated. To allow us to avoid having to manually update maps a system could be made where the maps are hosted on here and at the start of each server it would check to see if the map it had was up to date, if not it would load the new map.

**Comment by homiemace** [comment]
This would certainly be more efficient and take a load off, I like this idea a lot.

**Comment by Lanred-Dev** [comment]
This proposal is going to be taken back due to no way being found to execute this.

**Comment by Lanred-Dev** [comment]
This proposal is going to be taken back due to no way being found to execute this.
