### ISSUE TITLE
Should there be multiple bananas for currency icon instead of just one?

### ISSUE THREAD

**Issue by homiemace** [monke-mob/monke-activities#65]
### Proposal
I think we should use multiple bananas for the currency icon instead of just one. It makes more sense because it's uncommon to have just one unit of currency, and it also looks better in my opinion.

![bananabundlemediumsize](https://github.com/monke-mob/monke-activities/assets/90294477/12edbfd6-a114-449c-9675-456853f0f21e)
![bananasvgv6croppedmediumsize](https://github.com/monke-mob/monke-activities/assets/90294477/ab7af45e-8ebb-43a3-ad14-9498efc2e49c)

### Needed actions
As the SVG and AI files have already been created, you only need to replace the PNG files with the updated ones. This means that you don't have to make any changes to the vector graphics, and you can simply update the images.

_**Please list your comments below.**_

**Comment by Lanred-Dev** [comment]
Yes, I think so because one banana does not sell the idea of a currency but having multiple will sell the idea of currency.

**Comment by Chyrium** [comment]
idc

**Comment by Chyrium** [comment]
multiple

**Comment by bloxy1noob** [comment]
Normally when you see like a currency icon you see multiple of the icon, so I think it would be better to use the one with 3 bananas as the icon
