### ISSUE TITLE
New icon set to replace old ones.

### ISSUE THREAD

**Issue by homiemace** [monke-mob/monke-activities#8]
### Progress
- [x] Currency Icon
- [x] Shop Icon
- [x] Settings Icon
- [x] User Icon
- [x] Menu Icon
- [ ] Credits Icon
- [x] Codes Icon

Currently Remix Icons is used for all icons in the user interface. Instead we sould use custom icons made for just this game, to better fit the theme and remove potential copyright / ownership issues. Take for example the currency icon: It is currently a coin icon taken from Remix but we could replace it with a custom made currency icons that consists of bananas. Replacing that icon with bananas not only fits in with the game better but also removes potential copyright and ownership issues.

**Comment by homiemace** [comment]
With the new and improved "user" icon, I attempted to go with the face route like @Lanred-Dev said and it turned out alright I feel. I wish I could have somehow made it monkey-themed but it does its purpose and I feel is a good clean icon.

![image](https://github.com/monke-mob/monke-activities/assets/90294477/dbd4c525-ed3e-4f2e-83a1-965a336085a7)

**Comment by homiemace** [comment]
For the "settings" icon I used some YouTube tutorials considering I had absolutely no clue what I was doing, so although very basic I feel it works pretty well and I can improve it over time if needed.

![image](https://github.com/monke-mob/monke-activities/assets/90294477/127cf0f7-ebd6-48a1-88a5-ce4761b3c79b)

**Comment by Lanred-Dev** [comment]
> For the "settings" icon I used some YouTube tutorials considering I had absolutely no clue what I was doing, so although very basic I feel it works pretty well and I can improve it over time if needed.
> 
> 
> 
> ![image](https://github.com/monke-mob/monke-activities/assets/90294477/127cf0f7-ebd6-48a1-88a5-ce4761b3c79b)

I think that the circle in the center should be a little smaller.

**Comment by Lanred-Dev** [comment]
Changed priority to urgent so that this task can be closed.

**Comment by homiemace** [comment]
> For the "settings" icon I used some YouTube tutorials considering I had no clue what I was doing, so although very basic I feel it works pretty well and I can improve it over time if needed.

Completely redid the entire settings icon.

![image](https://github.com/monke-mob/monke-activities/assets/90294477/1082831f-6996-47f3-8a54-b0c4e2c985d7)

**Comment by homiemace** [comment]
Currency Icon
![bananasvgv6cropped](https://github.com/monke-mob/monke-activities/assets/90294477/bb8cb0b7-c996-46a7-903c-a8dc88eab521)

**Comment by homiemace** [comment]
Shop Icon
![bananashoppingbag5cropped](https://github.com/monke-mob/monke-activities/assets/90294477/c9c6d5d9-9633-4dd2-a20d-9dd0e4961cfd)

**Comment by homiemace** [comment]
Menu Icon
![menuicon3](https://github.com/monke-mob/monke-activities/assets/90294477/d4efb41d-2c3c-4be7-ad93-9fb325f5a69c)

**Comment by homiemace** [comment]
Codes Icon
![codesiconv1](https://github.com/monke-mob/monke-activities/assets/90294477/9e25e6f1-aa97-458b-981a-462e732756f0)

**Comment by homiemace** [comment]
> With the new and improved "user" icon, I attempted to go with the face route like @Lanred-Dev said and it turned out alright I feel. I wish I could have somehow made it monkey-themed but it does its purpose and I feel that it's a good clean icon.
> 

Redid face icon slightly:
![facev2](https://github.com/monke-mob/monke-activities/assets/90294477/220697c6-5953-4a85-bb59-c7ee41f8be6c)

**Comment by homiemace** [comment]
Credits icon
![creditsiconsquare](https://github.com/monke-mob/monke-activities/assets/90294477/42ced265-62f5-4a8e-b321-5a8942aad756)

**Comment by homiemace** [comment]
New settings icon
![settingsv5](https://github.com/monke-mob/monke-activities/assets/90294477/20b4580c-1a80-4d5e-80cb-55c455bf1bdd)
